version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/ # The destination on your EC2 instance
  - source: scripts/my-app.service
    destination: /etc/systemd/system/

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root