version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/my-app # The destination on your EC2 instance
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root